opt_in_rules:
  - force_unwrapping

disabled_rules:
 - nesting
 - class_delegate_protocol
 - type_name
 - trailing_whitespace

identifier_name:
  min_length: 2 
  max_length:
    warning: 40
    error: 50

excluded:
  - Pods

force_unwrapping: error
